dofile("test/network/address.lua")
dofile("test/network/resolve.lua")
dofile("test/network/socket.lua")
dofile("test/network/stream.lua")
dofile("test/network/datagram.lua")
dofile("test/network/connection.lua")
print("OK")